"""Detailed enemy / vehicle sprites with three views: down (front), side (facing right), up (back).
Left = mirrored side. Front/back views are symmetric: written as the left half incl. the centre column."""
import sys
sys.path.insert(0, __import__('os').path.dirname(__file__))
from sprites import make, C

P = dict(C)
P.update({
    'gob_l': (150, 222, 110), 'gob': (99, 182, 77), 'gob_d': (52, 120, 66), 'gob_dd': (30, 74, 52),
    'fur_l': (168, 178, 204), 'fur': (118, 128, 160), 'fur_d': (76, 84, 116), 'fur_dd': (48, 52, 78),
    'pink_l': (255, 178, 182), 'pink': (240, 128, 140),
    'sl_l': (176, 244, 140), 'sl': (99, 199, 77), 'sl_m': (62, 150, 72), 'sl_d': (38, 100, 66),
    'lea_l': (190, 130, 90), 'lea': (140, 88, 62), 'lea_d': (96, 58, 48),
})


def sym(half):
    return [r + r[:-1][::-1] for r in half]


def put(rows, x, y, patch):
    rows = list(rows)
    need = x + max(len(pr) for pr in patch)
    if need > len(rows[0]):   # grow the canvas to the right so the overlay fits
        rows = [r + '.' * (need - len(r)) for r in rows]
    for dy, pr in enumerate(patch):
        r = list(rows[y + dy])
        for dx, ch in enumerate(pr):
            if ch != '.':
                r[x + dx] = ch
        rows[y + dy] = ''.join(r)
    return rows


def render(rows, cmap):
    return make(rows, {k: P[v] if isinstance(v, str) else v for k, v in cmap.items()})


UNITS = {}

# ------------------------------------------------------------------ SLIME (class I)
SLIME_C = {'a': 'sl_l', 'L': 'sl', 'M': 'sl_m', 'D': 'sl_d', 'w': 'white', 'e': 'black', 'm': 'sl_d'}
UNITS['slime'] = dict(colors=SLIME_C, side=[
    ".....aaaa.....",
    "...aaLLLLaa...",
    "..aLwwLLLLLa..",
    ".aLwLLLLLLLLa.",
    ".LLLLLLLLeLLe.",
    "LLLLLLLLLeLLeL",
    "LLLLLLLLLLLmmL",
    "MLLLLLLLLLLLLM",
    ".MMMMMMMMMMMM.",
    "..DDDDDDDDDD..",
], down=sym([
    "....aaa",
    "..aaLLL",
    ".aLwLLL",
    ".LwLLLL",
    "LLLeLLL",
    "LLLeLLL",
    "LLLLLmm",
    "MLLLLLL",
    ".MMMMMM",
    "..DDDDD",
]), up=sym([
    "....aaa",
    "..aaLLL",
    ".aLwLLL",
    ".LwLLLL",
    "LLLLLLL",
    "LLLLLLL",
    "LLLLLLL",
    "MLLLLLL",
    ".MMMMMM",
    "..DDDDD",
]))

# ------------------------------------------------------------------ RAT (class I)
RAT_C = {'g': 'fur_l', 'G': 'fur', 'd': 'fur_d', 'p': 'pink', 'P': 'pink_l', 'e': 'black', 'n': 'pink',
         't': 'pink', 'w': 'white'}
UNITS['rat'] = dict(colors=RAT_C, side=[
    "...........pP...",
    "....gggggggpPd..",
    "..gGGGGGGGGGGGe.",
    "tGGGGGGGGGGGGGGn",
    "t.dGGGGGGGGGGd..",
    ".t.ddGGGGddd....",
    "....pp...pp.....",
], down=sym([
    "pP...",
    "pPgG.",
    ".gGGG",
    ".GeGG",
    ".GGGG",
    "..GGn",
    "..dGG",
    "...p.",
]), up=sym([
    "pP...",
    "pPgG.",
    ".gGGG",
    ".GGGG",
    ".GGGG",
    ".dGGG",
    "..dGG",
    "...pt",
]))

# ------------------------------------------------------------------ GOBLIN (class I)
GOBLIN_C = {'g': 'gob_l', 'G': 'gob', 'd': 'gob_d', 'e': 'gob_d', 'E': 'red_m', 'W': 'yellow', 'n': 'gob_d',
            't': 'white', 'L': 'lea', 'l': 'lea_d', 'B': 'xdbrown', 'y': 'gld', 'f': 'xdbrown', 'k': 'stl_l',
            'K': 'stl_d'}
UNITS['goblin'] = dict(colors=GOBLIN_C, side=[
    ".....ggg.....",
    "..e.gGGGGg...",
    "..eegGGGGGg..",
    "...eGGGGWEG..",
    "....GGGGGGGn.",
    "....dGGGGtd..",
    ".....dGGGd...",
    "....LLLLLL...",
    "...GLlLLLLGk.",
    "...GLlLLLLGkk",
    "....LlLLLL.K.",
    "....BBBBy....",
    "....LL.LL....",
    "....dd.dd....",
    "...ff..ff....",
], down=put(sym([
    "......g",
    "e...gGG",
    "ee.gGGG",
    ".eeGGGG",
    "...GWEG",
    "...GGGn",
    "...dGtt",
    "....dGG",
    "...LLLL",
    "..GLlLL",
    "..GLlLL",
    "...LLLL",
    "...BBBy",
    "...LL..",
    "...dd..",
    "..ff...",
]), 10, 8, ["k..", "kk.", ".K."]), up=put(sym([
    "......g",
    "e...gGG",
    "ee.gGGG",
    ".eeGGGG",
    "...GGGG",
    "...GGGG",
    "...dGGG",
    "....dGG",
    "...LLLL",
    "..GLLLL",
    "..GLLLL",
    "...LlLL",
    "...BBBB",
    "...LL..",
    "...dd..",
    "..ff...",
]), 0, 8, [".k", "kk", "K."]))

# ------------------------------------------------------------------ DIRE WOLF (class II)
WOLF_C = {'f': 'fur_l', 'F': 'fur', 'd': 'fur_d', 'D': 'fur_dd', 'e': 'fur_d', 'E': 'fur_dd', 'y': 'yellow',
          'n': 'black', 'w': 'white', 't': 'fur_d'}
UNITS['wolf'] = dict(colors=WOLF_C, side=[
    "...............ee...",
    "...............eEf..",
    "tt.ffffffffff.fFFFf.",
    ".tfFFFFFFFFFFFfFFyFn",
    "..FFFFFFFFFFFFFFFFww",
    "..FFFFFFFFFFFFFFdw..",
    "..dFFddddddddFFd....",
    "..FF.Fd....dF.FF....",
    "..Fd.Fd....dF.Fd....",
    "..DD.DD....DD.DD....",
], down=sym([
    "e.....",
    "eE....",
    "EfFFFF",
    "fFyFFF",
    "FFFFFF",
    ".FFFff",
    ".dFFfn",
    ".dFFww",
    ".FdFww",
    ".Fd.Fd",
    ".Fd.Fd",
    ".DD.DD",
]), up=sym([
    "e.....",
    "eE....",
    "EfFFFF",
    "fFFFFF",
    "FFFFFF",
    ".FFFFF",
    ".dFFFF",
    ".FFFFF",
    ".FdFdt",
    ".Fd.Ft",
    ".Fd.F.",
    ".DD.DD",
]))

# ------------------------------------------------------------------ IRONCLAD (class II, armored, red cape)
IRON_C = {'a': 'stl_l', 'A': 'stl', 's': 'stl_d', 'v': 'black', 'p': 'stl_l', 'P': 'stl_d', 'k': 'stl_dd',
          'O': 'stl_dd', 'r': 'red_m', 'R': 'gld', 'M': 'stl_d', 'm': 'stl_dd', 'L': 'stl', 'l': 'stl_d',
          'D': 'stl_d', 'd': 'stl_dd', 'c': 'red_m', 'C': 'red_d'}
UNITS['ironclad'] = dict(colors=IRON_C, side=[
    "....aaaa.......",
    "...aAAAAs......",
    "..aAAAAAAs.....",
    "..AAAAvvvs.....",
    "..AAAAAAAs.....",
    "...sAAAAs......",
    ".pPPPPPPPp.....",
    "cPPAAAAAPPOOO..",
    "cPAAAaAAPOrrrO.",
    "cCAAAAAAPOrRrO.",
    "cCAAAAAAAOrrrO.",
    "cCkAAAAAA.OOO..",
    ".CMMMMMMM......",
    "..mMmMmMm......",
    "..LLl.LLl......",
    "..LLl.LLl......",
    ".DDDd.DDDd.....",
], down=put(sym([
    "....aaaa",
    "...aAAAA",
    "..aAAAAA",
    "..AAvvvv",
    "..AAAAAA",
    "...sAAAA",
    ".pPPPPPP",
    "pPPAAAAA",
    "PPAAAaAA",
    ".PAAAAAA",
    ".AAAAAAA",
    ".kAAAAAA",
    "..MMMMMM",
    "..mMmMmM",
    "...LLl..",
    "...LLl..",
    "..DDDd..",
]), 10, 7, ["OOO..", "OrrrO", "OrRrO", "OrrrO", ".OOO."]), up=sym([
    "....aaaa",
    "...aAAAA",
    "..aAAAAA",
    "..AAAAAA",
    "..AAAAAA",
    "...sAAAA",
    ".pPPPPPP",
    "pPPccccc",
    "PPcccccc",
    ".Pcccccc",
    ".AcCcccc",
    ".kcCcccc",
    "..CCCCCC",
    "..mMmMmM",
    "...LLl..",
    "...LLl..",
    "..DDDd..",
]))

# ------------------------------------------------------------------ FIRE IMP (class II, fireproof)
IMP_C = {'h': 'hat_d', 'R': 'red_m', 'r': 'red_l', 'D': 'red_d', 'Y': 'yellow', 'n': 'red_d', 'w': 'white',
         'W': 'purple', 'V': 'magenta', 'o': 'org', 'f': 'red_d', 't': 'red_d', 'F': 'org', 'G': 'yellow'}
UNITS['imp'] = dict(colors=IMP_C, side=[
    ".....h..h....",
    ".....hhhh....",
    "....rRRRRR...",
    "....RRRRYRY..",
    "....RRRRRRRn.",
    "....DRRRwwD..",
    "VW...DRRRD...",
    "VWW.rRRRRR...",
    ".VWRRDDDRRo..",
    "..WRRDDDRRo..",
    "...RRRRRRR...",
    "...RR...RR...",
    "t..RR...RR...",
    "tt.ff...ff...",
    ".ttt.........",
    "..FG.........",
], down=sym([
    "...h..",
    "...hh.",
    "....rR",
    "...rRR",
    "...RYR",
    "...RRR",
    "...DRw",
    "VW..DR",
    "VWWrRR",
    ".VWRDD",
    "..oRDD",
    "...RRR",
    "...RR.",
    "...RR.",
    "...ff.",
]), up=sym([
    "...h..",
    "...hh.",
    "....rR",
    "...rRR",
    "...RRR",
    "...RRR",
    "...DRR",
    "VW..DR",
    "VWWVRR",
    ".VWVRR",
    "..oRRR",
    "...RRR",
    "...RRt",
    "...RRt",
    "...ffF",
]))

# ------------------------------------------------------------------ GOBLIN SHAMAN (class III, heals)
SHAMAN_C = {'F': 'red_m', 'f': 'gld', 'M': 'gld', 'm': 'gld_d', 'G': 'gob', 'g': 'gob_l', 'E': 'cyan',
            'd': 'gob_d', 't': 'white', 'n': 'gob_d', 'P': 'purple', 'p': 'magenta', 'k': 'sand', 'c': 'cyan',
            'C': 'blue', 's': 'wd', 'b': 'xdbrown'}
UNITS['shaman'] = dict(colors=SHAMAN_C, side=[
    "......Ff.......",
    ".....FfFF...c..",
    "....MMMMMM.cCc.",
    "...MmmmmmM..c..",
    "...mGGGGEm..s..",
    "....GGGGGn..s..",
    "....dGGtG...s..",
    "...PPPPPPP.Gs..",
    "..PPpPPPPPGGs..",
    "..PPpkPkPP..s..",
    "..PPpPPPPP..s..",
    "..PPpPPPPP..s..",
    "..PPpPPPPPP.s..",
    "..PPpPPPPPP.s..",
    "...PPPPPPP..s..",
    "...bb..bb......",
], down=put(sym([
    "......F",
    ".....Ff",
    "....MMM",
    "...Mmmm",
    "...mEGG",
    "....GGn",
    "....dGt",
    "...PPPP",
    "..PPpPP",
    "..PkPkP",
    "..PPpPP",
    "..PPpPP",
    "..PPpPP",
    "..PPpPP",
    "...PPPP",
    "...bb..",
]), 12, 0, [".c.", "cCc", ".c.", ".s.", ".s.", ".s.", ".s.", "Gs.", "Gs.", ".s.", ".s.", ".s.", ".s.", ".s.", ".s."]),
    up=put(sym([
    "......F",
    ".....Ff",
    "....MMM",
    "...MmmM",
    "...mmmm",
    "....GGG",
    "....dGG",
    "...PPPP",
    "..PPPPP",
    "..PPPPP",
    "..PPpPP",
    "..PPpPP",
    "..PPpPP",
    "..PPpPP",
    "...PPPP",
    "...bb..",
]), 0, 0, [".c.", "cCc", ".c.", ".s.", ".s.", ".s.", ".s.", ".sG", ".sG", ".s.", ".s.", ".s.", ".s.", ".s.", ".s."]))

# ------------------------------------------------------------------ OGRE (class III)
OGRE_C = {'G': 'tan', 'g': 'skin_l', 'd': 'skin_d', 'D': 'skin_dd', 'E': 'black', 'w': 'white', 'B': 'lea',
          'b': 'lea_d', 'W': 'xdbrown', 'F': 'xdbrown', 'c': 'wd', 'C': 'wd_d', 'k': 'stl'}
UNITS['ogre'] = dict(colors=OGRE_C, side=[
    "......gggggg........",
    ".....gGGGGGGG.......",
    ".....GGGGGGEGd......",
    ".....GGGGGGGGGd.....",
    "......dGGwGwGd......",
    "...ggGGGGGGGGGg..cc.",
    "..gGGGGGGGGGGGGg.ccc",
    ".gGGdBBBBBBBBGGGcckc",
    ".GGd.BBBBBBBBdGGccc.",
    ".GG..BBBbBBBB.dGcCc.",
    ".GG..BBBbBBBB..C....",
    ".dd..BBBbBBBB..C....",
    ".dd...WWWWWWW..C....",
    "......GGG.GGG.......",
    "......GGd.GGd.......",
    "......GGd.GGd.......",
    ".....FFFF.FFFF......",
], down=put(sym([
    "......gggg",
    ".....gGGGG",
    ".....GEGGG",
    ".....GGGGG",
    "......dGwG",
    "...ggGGGGG",
    "..gGGGGGGG",
    ".gGGdBBBBB",
    ".GGd.BBBBB",
    ".GG..BBBBb",
    ".GG..BBBBb",
    ".dd..BBBBb",
    ".dd...WWWW",
    "......GGG.",
    "......GGd.",
    "......GGd.",
    ".....FFFF.",
]), 16, 3, ["cc..", "ccc.", "ckc.", "ccc.", ".Cc.", ".C..", ".C..", ".C..", ".C.."]),
    up=put(sym([
    "......gggg",
    ".....gGGGG",
    ".....GGGGG",
    ".....GGGGG",
    "......dGGG",
    "...ggGGGGG",
    "..gGGGGGGG",
    ".gGGGGGGdd",
    ".GGdGGGGdG",
    ".GG.dGGGGG",
    ".GG..BBBBB",
    ".dd..BBBBB",
    ".dd...WWWW",
    "......GGG.",
    "......GGd.",
    "......GGd.",
    ".....FFFF.",
]), 0, 3, ["..cc", ".ccc", ".ckc", ".ccc", ".cC.", "..C.", "..C.", "..C.", "..C."]))

# ------------------------------------------------------------------ SLIME KING (class III, splits)
KING_C = {'y': 'gld', 'Y': 'gld_l', 'r': 'red_m', 'a': 'glass', 'L': 'blu', 'M': 'blu_d', 'D': 'dblue',
          'w': 'white', 'e': 'black', 'm': 'blu_d'}
UNITS['slime_king'] = dict(colors=KING_C, side=[
    "........y.y.y.......",
    "........yYrYy.......",
    "........yyyyy.......",
    ".....aaaaaaaaaa.....",
    "...aaLLLLLLLLLLaa...",
    "..aLwwLLLLLLLLLLLa..",
    ".aLwLLLLLLLLLeLLeLa.",
    ".LLLLLLLLLLLLeLLeLL.",
    "LLLLLLLLLLLLLLLLLLLL",
    "LLLLLLLLLLLLLLmmmLLL",
    "LLLLLLLLLLLLLLLLLLLL",
    "MLLLLLLLLLLLLLLLLLLM",
    ".MMMMMMMMMMMMMMMMMM.",
    "..DDDDDDDDDDDDDDDD..",
], down=sym([
    ".......y.y",
    ".......yYr",
    ".......yyy",
    "....aaaaaa",
    "..aaLLLLLL",
    ".aLwwLLLLL",
    "aLwLLLLLLL",
    "LLLLLeLLLL",
    "LLLLLeLLLL",
    "LLLLLLLLmm",
    "LLLLLLLLLL",
    "MLLLLLLLLL",
    ".MMMMMMMMM",
    "..DDDDDDDD",
]), up=sym([
    ".......y.y",
    ".......yyy",
    ".......yyy",
    "....aaaaaa",
    "..aaLLLLLL",
    ".aLwwLLLLL",
    "aLwLLLLLLL",
    "LLLLLLLLLL",
    "LLLLLLLLLL",
    "LLLLLLLLLL",
    "LLLLLLLLLL",
    "MLLLLLLLLL",
    ".MMMMMMMMM",
    "..DDDDDDDD",
]))

# ------------------------------------------------------------------ STONE GOLEM (class IV boss)
GOLEM_C = {'a': 'lgray', 'S': 'gray', 's': 'dgray', 'd': 'xdgray', 'c': 'cyan', 'm': 'blue', 'g': 'green'}
UNITS['golem'] = dict(colors=GOLEM_C, side=[
    "..........aaaa........",
    ".........aSSSSs.......",
    ".........SSSSSS.......",
    ".........SSSScSS......",
    ".........SSSSSSS......",
    "..........sSSSs.......",
    "....aaaaaaSSSSaaa.....",
    "...aSSSSSSSSSSSSSa....",
    "..aSSSSSSSSSSSSSSSS...",
    "..SSSgSSSSSSSSmmSSSS..",
    "..SSgSSSSsSSSSmcSSSS..",
    "..SSSSSSSsSSSSSSS.SSS.",
    "..SSSSSSSSsSSSSSS.SSS.",
    "...ssSSSSSSSSSSSS.sSSs",
    "...ss.SSSSSSSSSS..ssss",
    "......SSSS..SSSS......",
    "......SSSs..SSSs......",
    ".....SSSSs..SSSSs.....",
    ".....ddddd..ddddd.....",
], down=sym([
    "..........aaa",
    ".........aSSS",
    ".........SSSS",
    ".........ScSS",
    ".........SSSS",
    "..........sSS",
    "...aaaa...SSS",
    "..aSSSSaaSSSS",
    ".aSSSSSSSSSSS",
    ".SSgSsSSSSSmm",
    ".SgSS.SSsSSmc",
    ".SSSS.SSSsSmm",
    ".SSSS.SSSSSSS",
    ".ssss.SSSSSSS",
    ".ssss.SSSSsSS",
    "......SSSS...",
    "......SSSs...",
    ".....SSSSs...",
    ".....ddddd...",
]), up=sym([
    "..........aaa",
    ".........aSSS",
    ".........SSSS",
    ".........SSSS",
    ".........SSSS",
    "..........sSS",
    "...aaaa...SSS",
    "..aSSSSaaSSSS",
    ".aSSSSSSSsSSS",
    ".SSgSsSSSSsSS",
    ".SgSS.SSsSSsS",
    ".SSSS.SSSsSSs",
    ".SSSS.SSgSSSS",
    ".ssss.SSggSSS",
    ".ssss.SSSSsSS",
    "......SSSS...",
    "......SSSs...",
    ".....SSSSs...",
    ".....ddddd...",
]))

# ------------------------------------------------------------------ DEMON LORD (class IV final boss)
DEMON_C = {'h': 'sand', 'H': 'tan', 'R': 'red_m', 'r': 'red_l', 'D': 'red_d', 'Y': 'yellow', 'w': 'white',
           'W': 'purple', 'V': 'magenta', 'A': 'black', 'a': 'xdgray', 'f': 'black', 'G': 'gld'}
UNITS['demon'] = dict(colors=DEMON_C, side=[
    "...............hh...........",
    "..............hhh...........",
    ".............hhRRRRR........",
    "............hhrRRRRRR.......",
    "..............RRRRRYRY......",
    "..............RRRRRRRRR.....",
    "..WW...........RRRwRwD......",
    ".WWVW...........DRRRD.......",
    "WWVVWW.......rRRRRRRRRR.....",
    "WVVVVWW....rRRRRRRRRRRRR....",
    "WVVVVVWW..RRRRaaaaaaRRRRR...",
    ".WVVVVVWWRRRRaAAGAAaRRRRR...",
    "..WVVVVVWRRRRaAAAAAaRR.RR...",
    "...WVVVVWRRRRaAAAAAaRR.RRr..",
    "....WVVVWRRRRRaaaaaRR..RRr..",
    ".....WVVWRRRRRRRRRRRR..DDD..",
    "......WWW.RRRRRRRRRR........",
    "...........RRRR..RRRR.......",
    "...........RRRD..RRRD.......",
    "...........RRRD..RRRD.......",
    "..........ffff..ffff........",
], down=sym([
    "..h...........",
    "..hh..........",
    "...hh.....RRRR",
    "....hhh..rRRRR",
    "......hhRRRRRR",
    "........RYYRRR",
    "........RRRRRR",
    ".........RwRRw",
    "..........DRRR",
    "WW......rRRRRR",
    "WVW...rRRRRRRR",
    "WVVW.RRRRaaaaa",
    "WVVVWRRRRaAAAA",
    "WVVVWRR.RaAAAG",
    ".WVVWRR.RaAAAA",
    "..WVWRR.RRaaaa",
    "...WWDDD.RRRRR",
    ".........RRRR.",
    ".........RRRD.",
    ".........RRRD.",
    "........ffff..",
]), up=sym([
    "..h...........",
    "..hh..........",
    "...hh.....RRRR",
    "....hhh..rRRRR",
    "......hhRRRRRR",
    "........RRRRRR",
    "........RRRRRR",
    ".........RRRRR",
    "..........DRRR",
    "WW......WWRRRR",
    "WVW...WWVVWRRR",
    "WVVW.WVVVVVWRR",
    "WVVVWVVVVVVVWR",
    "WVVVWVVVVVVVVW",
    ".WVVWVVVVVVVVW",
    "..WVWRWVVVVVWR",
    "...WWDDWWWWWRR",
    ".........RRRR.",
    ".........RRRD.",
    ".........RRRD.",
    "........ffff..",
]))

# ------------------------------------------------------------------ FRIENDLY VEHICLES (garage)
CAR_C = {'r': 'red_l', 'R': 'red_m', 'D': 'red_d', 'c': 'glass', 'd': 'glass_d', 'y': 'yellow', 'k': 'black',
         'g': 'gray', 'p': 'pink', 'w': 'white', 'C': 'glass_d'}
UNITS['car'] = dict(colors=CAR_C, side=[
    "....rrrrr.....",
    "...RccRcdR....",
    "..RccdRccdR...",
    "rrrrrrrrrrrrry",
    "RRRRRRRRRRRRRR",
    "RDDRRRRRRDDRRD",
    ".kgk.....kgk..",
    ".kkk.....kkk..",
], down=sym([
    "..rrr",
    ".RccC",
    ".Rccc",
    "rrrrr",
    "yRRRR",
    "RDDDD",
    "kk...",
]), up=sym([
    "..rrr",
    ".RCCC",
    ".RRRR",
    "rrrrr",
    "pRRRR",
    "RRRww",
    "kk...",
]))

PICKUP_C = {'b': 'blu_l', 'B': 'blu', 'D': 'blu_d', 'c': 'glass', 'C': 'glass_d', 'y': 'yellow', 'k': 'black',
            'g': 'gray', 'p': 'pink', 'w': 'white', 'o': 'wd'}
UNITS['pickup'] = dict(colors=PICKUP_C, side=[
    "........bbbbb...",
    ".......BccBcC...",
    "......BcccBccB..",
    "bbbbbbbbbbbbbbby",
    "BooooBBBBBBBBBBB",
    "BBBBBBBBBBBBBBBB",
    "BDDBBBBBBBBDDBBD",
    ".kgk......kgk...",
    ".kkk......kkk...",
], down=sym([
    "...bbb",
    "..BccC",
    "..Bccc",
    "bbbbbb",
    "yBBBBB",
    "BDDDDD",
    "kk....",
]), up=sym([
    "...bbb",
    "..BCCC",
    "Bbbbbb",
    "Boooooo"[:6],
    "BBBBBB",
    "pBBBww",
    "kk....",
]))

TRUCK_C = {'W': 'lgray', 'w': 'white', 'S': 'gray', 'o': 'org_l', 'O': 'org', 'D': 'org_d', 'c': 'glass',
           'C': 'glass_d', 'y': 'yellow', 'k': 'black', 'g': 'gray', 'p': 'pink', 'b': 'blu'}
UNITS['truck'] = dict(colors=TRUCK_C, side=[
    "wwwwwwwwwww.......",
    "WWWWWWWWWWW.ooo...",
    "WWbbbbbbbWW.OccO..",
    "WWWWWWWWWWW.OcCOO.",
    "WWWWWWWWWWWOOOOOOy",
    "SSSSSSSSSSSOOOOOOO",
    "SSSSSSSSSSSDOOOOOD",
    "SkgkSkgkSSSSSkgkSS",
    ".kkk.kkk.....kkk..",
], down=sym([
    "wwwwww",
    "WWWWWW",
    "WoOOOO",
    "WOcccc",
    "WOcccC",
    "yOOOOO",
    "SDDDDD",
    "kk....",
]), up=sym([
    "wwwwww",
    "WWWWWW",
    "WWWWWW",
    "WWWWWS",
    "WWWWWS",
    "pWWWWS",
    "SSSSww",
    "kk....",
]))

ARMORED_C = {'g': 'olv_l', 'G': 'olv', 'D': 'olv_d', 'E': 'olv_dd', 'k': 'black', 'h': 'gray', 'b': 'gun',
             'B': 'gun_d', 'y': 'yellow', 'p': 'pink', 'c': 'glass_d'}
UNITS['armored'] = dict(colors=ARMORED_C, side=[
    "......ggggg.......",
    ".....gGGGGGbbbbbB.",
    ".....DDDDDDD......",
    "..gggggggggggggg..",
    ".gGGGGGGGGGGccGGg.",
    "gGGGgGGGGgGGGGGGGy",
    "GGGGGGGGGGGGGGGGGG",
    "DDDDDDDDDDDDDDDDDD",
    "EkhkEkhkEEkhkEkhkE",
    ".kkk.kkk..kkk.kkk.",
], down=put(sym([
    "....ggg",
    "...gGGG",
    "...DDbD",
    ".gggggg",
    "gGcccGG",
    "yGGGGGG",
    "DDDDDDD",
    "kk.....",
]), 6, 0, ["b", "b"]), up=sym([
    "....ggg",
    "...gGGG",
    "...DDDD",
    ".gggggg",
    "gGGGGGG",
    "pGGgGGG",
    "DDDDDDD",
    "kk.....",
]))
